---
# milestone 1 - Installing Java
- name: install Java
  debug: msg="SDK 8"
  
- block:
    #- name: install Oracle JDK on Ubuntu
    - name: Add Oracle Java Repository
      apt_repository: repo='ppa:webupd8team/java' state=present
    - name: update apt  
      apt: update_cache=yes
      
    - name: Accept oracle license
      debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
        
    - name: Install Oracle Java 8 JDK  
      become: yes
      apt: name="{{item}}" state=latest
      with_items:
        - "oracle-java8-installer"
        - "ca-certificates"
        - "oracle-java8-set-default"    
    - name: "Export {{ JAVA_HOME }}"
      shell: "export JAVA_HOME={{ JAVA_HOME }}"

    - name: A workaround to get tomcat7 installed on Ubuntu 16.04
      template:
        src: etc_default_tomcat7.j2
        dest: /etc/default/tomcat7
      when: ansible_distribution_release == "xenial"
    - name: Set JAVA_HOME in /etc/environment
      lineinfile:
        dest: /etc/environment
        regexp: "JAVA_HOME={{ JAVA_HOME }}"
        line: "JAVA_HOME={{ JAVA_HOME }}"
  when: ansible_os_family == 'Debian'